name: Bazel Sample

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move to repo root
      - run: |
          cd $GITHUB_WORKSPACE

      - name: Build with Bazel
        run: |
          cd $GITHUB_WORKSPACE
          bazel build //:hello

      - name: Run binary
        run: |
          cd $GITHUB_WORKSPACE
          bazel run //:hello


