name: Cache
on: push
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4                         # キャッシュの復元と保存
        with:
          key: test-${{ runner.os }} # キャッシュキー
          path: ${{ github.workspace }}/dummy          # キャッシュ対象のパス
          restore-keys: |                              # リストアキー
            test-${{ runner.os }}-
      - run: |
          if [[ -f "${GITHUB_WORKSPACE}/dummy" ]]; then
            echo "Cache Hit!"
            exit 0
          fi
          echo "NO CACHE!"
          dd if=/dev/urandom of="${GITHUB_WORKSPACE}/dummy" bs=1M count=10
          sleep 30
      - run: ls -lh "${GITHUB_WORKSPACE}/dummy"
